# vim: set ft=nginx:

resolver         {{ default "8.8.8.8" .Env.STACK_RESOLVER }} valid={{ default "300" .Env.STACK_RESOLVER_VALID }}s ipv6=off;
resolver_timeout {{ default "10" .Env.STACK_RESOLVER_TIMEOUT }}s;
